/* ================================================================
   DOGEARED — catalog.js
   Seed data: genres, moods, a starter catalog (works offline),
   quotes, achievements, XP rules, journal prompts.
   Icons are icon-system names (see icons.js) — no emoji here,
   except SESSION_MOODS which intentionally stay as emoji.
================================================================ */
"use strict";

const GENRES = [
  { id: "fantasy",   label: "Fantasy",          ic: "sparkle" },
  { id: "scifi",     label: "Sci-Fi",           ic: "rocket" },
  { id: "romance",   label: "Romance",          ic: "heart" },
  { id: "mystery",   label: "Mystery & Thriller", ic: "search" },
  { id: "litfic",    label: "Literary Fiction", ic: "feather" },
  { id: "historical",label: "Historical",       ic: "landmark" },
  { id: "horror",    label: "Horror",           ic: "moon" },
  { id: "nonfic",    label: "Non-fiction",      ic: "lightbulb" },
  { id: "growth",    label: "Self-Growth",      ic: "sprout" },
  { id: "classics",  label: "Classics",         ic: "book_open" },
  { id: "ya",        label: "Young Adult",      ic: "star" },
  { id: "poetry",    label: "Poetry & Essays",  ic: "pen" },
];

const MOODS = [
  { id: "cozy",     label: "Cozy & comforting",   ic: "coffee" },
  { id: "dark",     label: "Dark & atmospheric",  ic: "moon" },
  { id: "twisty",   label: "Fast & twisty",       ic: "shuffle" },
  { id: "feels",    label: "Big feelings",        ic: "heart" },
  { id: "mind",     label: "Mind-expanding",      ic: "lightbulb" },
  { id: "whimsy",   label: "Whimsical & light",   ic: "wind" },
  { id: "slowburn", label: "Slow burn",           ic: "sunrise" },
  { id: "epic",     label: "Epic adventure",      ic: "mountain" },
];

/* genre → solid brand-tinted color (no gradients) */
const GENRE_HUES = {
  fantasy: "#3A3A3E", scifi: "#4A4A4E", romance: "#57575C", mystery: "#2E2E32",
  litfic: "#65656A", historical: "#454549", horror: "#242427", nonfic: "#525258",
  growth: "#606066", classics: "#3E3E42", ya: "#4E4E54", poetry: "#5C5C62",
};

/* Starter catalog — powers Discover offline & seeds recommendations. */
const CATALOG = [
  { id:"c1",  t:"The Name of the Wind", a:"Patrick Rothfuss", g:["fantasy"], m:["epic","slowburn"], p:662, y:2007, r:4.5, b:"A legendary arcanist recounts how a gifted, grieving boy talked his way into a university of magic — and into myth." },
  { id:"c2",  t:"A Wizard of Earthsea", a:"Ursula K. Le Guin", g:["fantasy","classics"], m:["mind","epic"], p:183, y:1968, r:4.0, b:"A young mage's pride looses a shadow on the world, and the hunt to name it becomes a hunt for himself." },
  { id:"c3",  t:"The House in the Cerulean Sea", a:"TJ Klune", g:["fantasy","romance"], m:["cozy","whimsy"], p:396, y:2020, r:4.4, b:"A by-the-book caseworker audits an orphanage of magical children and finds his rulebook melting." },
  { id:"c4",  t:"Piranesi", a:"Susanna Clarke", g:["fantasy","litfic"], m:["mind","dark"], p:245, y:2020, r:4.2, b:"A gentle man wanders an infinite house of statues and tides, cataloguing a world that is not what he thinks." },
  { id:"c5",  t:"The Fifth Season", a:"N.K. Jemisin", g:["fantasy","scifi"], m:["dark","epic"], p:468, y:2015, r:4.3, b:"On a planet that keeps trying to die, a mother with earth-shattering power crosses a broken land." },
  { id:"c6",  t:"Project Hail Mary", a:"Andy Weir", g:["scifi"], m:["mind","twisty"], p:476, y:2021, r:4.5, b:"A man wakes alone on a starship with no memory and one job: save a species. Possibly two." },
  { id:"c7",  t:"Dune", a:"Frank Herbert", g:["scifi","classics"], m:["epic","mind"], p:412, y:1965, r:4.3, b:"A desert planet, a hunted heir, and the most dangerous substance in the universe: belief." },
  { id:"c8",  t:"The Left Hand of Darkness", a:"Ursula K. Le Guin", g:["scifi","classics"], m:["mind","slowburn"], p:304, y:1969, r:4.1, b:"An envoy alone on a winter planet learns that politics, gender, and loyalty are all shapeshifters." },
  { id:"c9",  t:"Klara and the Sun", a:"Kazuo Ishiguro", g:["scifi","litfic"], m:["feels","slowburn"], p:303, y:2021, r:3.9, b:"An artificial friend watches the sun, and the humans she loves, with devastating sincerity." },
  { id:"c10", t:"Sea of Tranquility", a:"Emily St. John Mandel", g:["scifi","litfic"], m:["mind","feels"], p:255, y:2022, r:4.1, b:"A moment glitches across five centuries, stitching exiles, pandemics, and moon colonies together." },
  { id:"c11", t:"Beach Read", a:"Emily Henry", g:["romance"], m:["cozy","feels"], p:361, y:2020, r:4.0, b:"Two rival writers swap genres for a summer and discover the plot twist is each other." },
  { id:"c12", t:"Red, White & Royal Blue", a:"Casey McQuiston", g:["romance"], m:["whimsy","feels"], p:421, y:2019, r:4.1, b:"The First Son of the US and a British prince go from tabloid feud to international secret." },
  { id:"c13", t:"Pride and Prejudice", a:"Jane Austen", g:["romance","classics"], m:["whimsy","slowburn"], p:279, y:1813, r:4.3, b:"The sharpest tongue in Hertfordshire meets the proudest man in England. Sparks, verbally, fly." },
  { id:"c14", t:"The Seven Husbands of Evelyn Hugo", a:"Taylor Jenkins Reid", g:["romance","litfic"], m:["feels","twisty"], p:389, y:2017, r:4.4, b:"A reclusive Hollywood icon finally tells the truth about seven marriages and one great love." },
  { id:"c15", t:"Gone Girl", a:"Gillian Flynn", g:["mystery"], m:["twisty","dark"], p:415, y:2012, r:4.1, b:"A wife disappears on her anniversary and every chapter makes you switch whose side you're on." },
  { id:"c16", t:"The Silent Patient", a:"Alex Michaelides", g:["mystery"], m:["twisty","dark"], p:325, y:2019, r:4.2, b:"She shot her husband and never spoke again. Her new therapist is determined to know why." },
  { id:"c17", t:"And Then There Were None", a:"Agatha Christie", g:["mystery","classics"], m:["twisty","dark"], p:264, y:1939, r:4.3, b:"Ten strangers, one island, zero survivors promised. The blueprint for every thriller since." },
  { id:"c18", t:"The Thursday Murder Club", a:"Richard Osman", g:["mystery"], m:["cozy","whimsy"], p:382, y:2020, r:4.1, b:"Four retirees who solve cold cases for fun suddenly get a warm one, right on their doorstep." },
  { id:"c19", t:"A Little Life", a:"Hanya Yanagihara", g:["litfic"], m:["feels","dark"], p:720, y:2015, r:4.3, b:"Four friends across four decades, and one man whose past keeps the reader holding their breath." },
  { id:"c20", t:"Normal People", a:"Sally Rooney", g:["litfic","romance"], m:["feels","slowburn"], p:266, y:2018, r:3.8, b:"Two people who understand each other completely, except whenever it matters most." },
  { id:"c21", t:"The Remains of the Day", a:"Kazuo Ishiguro", g:["litfic","classics"], m:["slowburn","feels"], p:258, y:1989, r:4.1, b:"A butler drives across England and, very politely, realizes he may have missed his whole life." },
  { id:"c22", t:"Tomorrow, and Tomorrow, and Tomorrow", a:"Gabrielle Zevin", g:["litfic"], m:["feels","mind"], p:401, y:2022, r:4.2, b:"Two friends build video games together for thirty years. A love story that isn't a romance." },
  { id:"c23", t:"Pachinko", a:"Min Jin Lee", g:["historical","litfic"], m:["feels","epic"], p:490, y:2017, r:4.3, b:"Four generations of a Korean family in Japan, carrying history in their pockets like warm coins." },
  { id:"c24", t:"All the Light We Cannot See", a:"Anthony Doerr", g:["historical"], m:["feels","slowburn"], p:531, y:2014, r:4.2, b:"A blind French girl and a German radio prodigy drift toward each other through occupied Europe." },
  { id:"c25", t:"Wolf Hall", a:"Hilary Mantel", g:["historical"], m:["slowburn","mind"], p:604, y:2009, r:3.9, b:"Thomas Cromwell rises through Henry VIII's court on wit alone, in prose sharp enough to shave with." },
  { id:"c26", t:"The Book Thief", a:"Markus Zusak", g:["historical","ya"], m:["feels","dark"], p:552, y:2005, r:4.4, b:"Death himself narrates the story of a girl in Nazi Germany who steals books and shares them." },
  { id:"c27", t:"Mexican Gothic", a:"Silvia Moreno-Garcia", g:["horror","historical"], m:["dark","twisty"], p:301, y:2020, r:3.7, b:"A glamorous socialite visits her cousin's decaying mansion and the house starts dreaming back." },
  { id:"c28", t:"The Haunting of Hill House", a:"Shirley Jackson", g:["horror","classics"], m:["dark","slowburn"], p:246, y:1959, r:4.0, b:"Four people spend a summer in a house that was born bad. Not everyone checks out." },
  { id:"c29", t:"House of Leaves", a:"Mark Z. Danielewski", g:["horror"], m:["mind","dark"], p:705, y:2000, r:4.1, b:"A house is bigger on the inside, and the book about it starts rearranging your margins." },
  { id:"c30", t:"Sapiens", a:"Yuval Noah Harari", g:["nonfic"], m:["mind"], p:443, y:2011, r:4.3, b:"How a gossiping ape invented money, gods, and nations — a whirlwind tour of us." },
  { id:"c31", t:"Educated", a:"Tara Westover", g:["nonfic"], m:["feels","dark"], p:334, y:2018, r:4.5, b:"Raised off-grid by survivalists, she first set foot in a classroom at seventeen. Then Cambridge." },
  { id:"c32", t:"Thinking, Fast and Slow", a:"Daniel Kahneman", g:["nonfic","growth"], m:["mind"], p:499, y:2011, r:4.1, b:"A Nobel laureate explains the two characters in your head and why they keep fooling you." },
  { id:"c33", t:"The Body Keeps the Score", a:"Bessel van der Kolk", g:["nonfic","growth"], m:["mind","feels"], p:445, y:2014, r:4.4, b:"How trauma lives in the body, and the surprising paths through which people heal." },
  { id:"c34", t:"Atomic Habits", a:"James Clear", g:["growth"], m:["mind"], p:319, y:2018, r:4.3, b:"Forget goals; design systems. The 1%-better handbook that launched a million routines." },
  { id:"c35", t:"Deep Work", a:"Cal Newport", g:["growth","nonfic"], m:["mind"], p:296, y:2016, r:4.1, b:"A case for focus as a superpower in a world engineered to shatter it." },
  { id:"c36", t:"The Alchemist", a:"Paulo Coelho", g:["growth","classics"], m:["whimsy","mind"], p:197, y:1988, r:3.9, b:"A shepherd chases a recurring dream to the pyramids and finds the treasure was the detour." },
  { id:"c37", t:"East of Eden", a:"John Steinbeck", g:["classics","litfic"], m:["epic","feels"], p:601, y:1952, r:4.4, b:"Two families reenact Cain and Abel in a California valley. Timshel: thou mayest." },
  { id:"c38", t:"Jane Eyre", a:"Charlotte Brontë", g:["classics","romance"], m:["dark","slowburn"], p:507, y:1847, r:4.2, b:"A governess with an iron will, an employer with a locked attic, and a moor full of secrets." },
  { id:"c39", t:"One Hundred Years of Solitude", a:"Gabriel García Márquez", g:["classics","litfic"], m:["mind","whimsy"], p:417, y:1967, r:4.1, b:"A century of the Buendía family in a town where rain lasts years and ghosts hold grudges." },
  { id:"c40", t:"Six of Crows", a:"Leigh Bardugo", g:["ya","fantasy"], m:["twisty","epic"], p:465, y:2015, r:4.5, b:"Six dangerous outcasts, one impossible heist, and a criminal prodigy who's always six steps ahead." },
  { id:"c41", t:"The Hunger Games", a:"Suzanne Collins", g:["ya","scifi"], m:["twisty","epic"], p:374, y:2008, r:4.3, b:"A girl volunteers for a televised death match and accidentally sparks a revolution." },
  { id:"c42", t:"They Both Die at the End", a:"Adam Silvera", g:["ya","romance"], m:["feels"], p:373, y:2017, r:4.0, b:"Two strangers get the call that today is their last day, and decide to spend it living." },
  { id:"c43", t:"Milk and Honey", a:"Rupi Kaur", g:["poetry"], m:["feels"], p:204, y:2014, r:3.8, b:"Spare verses on hurting, loving, breaking, and healing — a phenomenon in four chapters." },
  { id:"c44", t:"Devotions", a:"Mary Oliver", g:["poetry"], m:["cozy","mind"], p:442, y:2017, r:4.6, b:"A lifetime of paying attention: geese, grasshoppers, and your one wild and precious life." },
  { id:"c45", t:"The Midnight Library", a:"Matt Haig", g:["litfic","fantasy"], m:["feels","whimsy"], p:288, y:2020, r:4.0, b:"Between life and death is a library of the lives you didn't live. Nora starts browsing." },
  { id:"c46", t:"Circe", a:"Madeline Miller", g:["fantasy","historical"], m:["feels","epic"], p:393, y:2018, r:4.3, b:"The witch of Greek myth gets the whole stage: exile, monsters, gods, and a hard-won self." },
  { id:"c47", t:"The Martian", a:"Andy Weir", g:["scifi"], m:["twisty","whimsy"], p:369, y:2011, r:4.4, b:"An astronaut is left for dead on Mars and decides to science the daylights out of it." },
  { id:"c48", t:"Before the Coffee Gets Cold", a:"Toshikazu Kawaguchi", g:["litfic","fantasy"], m:["cozy","feels"], p:213, y:2015, r:3.7, b:"A Tokyo café lets you travel back in time — but only until your coffee goes cold." },
];

const QUOTES = [
  ["A person who never made a mistake never tried anything new.", "Albert Einstein", null],
  ["The only impossible journey is the one you never begin.", "Tony Robbins", null],
  ["The unread story is not a story; it is little black marks on wood pulp. The reader, reading it, makes it live.", "Ursula K. Le Guin", null],
  ["Learning never exhausts the mind.", "Leonardo da Vinci", null],
  ["A classic is a successful book that has survived the reaction of the next generation.", "F. Scott Fitzgerald", "The Beautiful and Damned"],
  ["Isn't it nice to think that tomorrow is a new day with no mistakes in it yet?", "L.M. Montgomery", "Anne of Green Gables"],
  ["A word is not the same with one writer as with another. One tears it from his guts. The other pulls it out of his overcoat pocket.", "Charles Péguy", null],
  ["I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.", "Groucho Marx", null],
  ["So long, and thanks for all the fish.", "Douglas Adams", null],
  ["The story so far: In the beginning the universe was created. This has made a lot of people very angry and been widely regarded as a bad move.", "Douglas Adams", "The Restaurant at the End of the Universe"],
  ["Once you've read a book you care about, some part of it is always with you.", "Louis L'Amour", null],
  ["I am no bird; and no net ensnares me: I am a free human being with an independent will.", "Charlotte Brontë", "Jane Eyre"],
  ["Season of mists and mellow fruitfulness.", "John Keats", "To Autumn"],
  ["I feel the need of reading. It is a loss to a man not to have grown up among books.", "Abraham Lincoln", null],
  ["Peace comes from within. Do not seek it without.", "Buddha", null],
  ["The mind is everything. What you think you become.", "Buddha", null],
  ["I hear and I forget; I see and I remember; I write and I understand.", "Chinese proverb", null],
  ["I am no bird, and no net ensnares me.", "Charlotte Brontë", "Jane Eyre"],
  ["I was made for the library, not the classroom. The library was open, unending, free.", "Ta-Nehisi Coates", null],
  ["Every book is a little mirror, and sometimes you look into it and see someone else looking back.", "Travis Baldree", "Bookshops & Bonedust"],
  ["Try not to become a man of success, but rather try to become a man of value.", "Albert Einstein", null],
  ["Wise men speak because they have something to say; fools because they have to say something.", "Plato", null],
  ["Life is what happens when you're busy making other plans.", "John Lennon", null],
  ["Light is the left hand of darkness, and darkness the right hand of light.", "Ursula K. Le Guin", "The Left Hand of Darkness"],
  ["It is good to have an end to journey toward, but it is the journey that matters in the end.", "Ursula K. Le Guin", null],
  ["Words can be like X-rays if you use them properly — they'll go through anything.", "Aldous Huxley", "Brave New World"],
  ["A book must be the axe for the frozen sea within us.", "Franz Kafka", null],
  ["A book, tight shut, is but a block of paper... but when a book is opened, one page draws to another, and while it lasts, that reader is a mightier being.", "Rumer Godden", null],
  ["I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", "Sylvia Plath", "The Bell Jar"],
  ["It was a pleasure to burn.", "Ray Bradbury", "Fahrenheit 451"],
  ["Show me a family of readers, and I will show you the people who move the world.", "Napoléon Bonaparte", null],
  ["A library is a miracle — a place where your mind can come alive.", "Josh Hanagarne", "The World's Strongest Librarian"],
  ["It matters not how strait the gate, how charged with punishments the scroll — I am the master of my fate.", "William Ernest Henley", "Invictus"],
  ["What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson", null],
  ["You can make anything by writing.", "C.S. Lewis", null],
  ["Every morning we are born again. What we do today is what matters most.", "Buddha", null],
  ["The whole is greater than the sum of its parts.", "Aristotle", null],
  ["It is with true love as it is with ghosts; everyone talks of it, but few have seen it.", "François de La Rochefoucauld", null],
  ["There is no Frigate like a Book to take us Lands away.", "Emily Dickinson", null],
  ["There is more treasure in books than in all the pirate's loot.", "Walt Disney", null],
  ["Sometimes you read a book and it fills you with this weird evangelical zeal.", "John Green", "The Fault in Our Stars"],
  ["For small creatures such as we, the vastness is bearable only through love.", "Carl Sagan", "Contact"],
  ["A children's story that can only be enjoyed by children is not a good children's story.", "C.S. Lewis", null],
  ["It's the questions we can't answer that teach us the most.", "Patrick Rothfuss", "The Wise Man's Fear"],
  ["The person who deserves most pity is a lonesome one on a rainy day who doesn't know how to read.", "Benjamin Franklin", null],
  ["You become responsible, forever, for what you have tamed.", "Antoine de Saint-Exupéry", "The Little Prince"],
  ["It is well known that reading quickens the growth of a heart like nothing else.", "Catherynne M. Valente", "The Girl Who Circumnavigated Fairyland in a Ship of Her Own Making"],
  ["An unexamined life is not worth living, but a life too closely examined may not be lived at all.", "Ann Patchett", null],
  ["All happy families are alike; each unhappy family is unhappy in its own way.", "Leo Tolstoy", "Anna Karenina"],
  ["There must be something in books, something we can't imagine, to make a woman stay in a burning house.", "Ray Bradbury", "Fahrenheit 451"],
  ["Read, read, read. Read everything — trash, classics, good and bad — and see how they do it.", "William Faulkner", null],
  ["Independent inquiry is needed in your search for truth, not dependence on someone else's view.", "Bruce Lee", null],
  ["Never lend books, for no one ever returns them; the only books I have in my library are books that other folks have left me.", "Anatole France", null],
  ["For every minute you remain angry, you give up sixty seconds of peace of mind.", "Ralph Waldo Emerson", null],
  ["There is some good in this world, and it's worth fighting for.", "J.R.R. Tolkien", "The Two Towers"],
  ["Books are the treasured wealth of the world and the fit inheritance of generations and nations.", "Henry David Thoreau", "Walden"],
  ["It always seems impossible until it's done.", "Nelson Mandela", null],
  ["The journey of a thousand miles begins with a single step.", "Lao Tzu", "Tao Te Ching"],
  ["We're all mad here.", "Lewis Carroll", "Alice's Adventures in Wonderland"],
  ["The library card is a passport to wonders and miracles, glimpses into other lives.", "Libba Bray", null],
  ["Reading gives us someplace to go when we have to stay where we are.", "Mason Cooley", null],
  ["Let yourself be silently drawn by the strange pull of what you really love.", "Rumi", null],
  ["A ship would not go there, safe harbor, if it always followed the safest course.", "Ursula K. Le Guin", null],
  ["There are books so alive that you're always afraid that while you weren't reading, the book has changed.", "Marina Tsvetaeva", null],
  ["The child is father of the man.", "William Wordsworth", null],
  ["The only way out of the labyrinth of suffering is to forgive.", "John Green", "Looking for Alaska"],
  ["Do not go gentle into that good night.", "Dylan Thomas", null],
  ["A thing of beauty is a joy forever.", "John Keats", "Endymion"],
  ["It does not do to dwell on dreams and forget to live.", "J.K. Rowling", "Harry Potter and the Sorcerer's Stone"],
  ["Libraries were full of ideas — perhaps the most dangerous and powerful of all weapons.", "Sarah J. Maas", null],
  ["Fill your paper with the breathings of your heart.", "William Wordsworth", null],
  ["Books must be read as deliberately and reservedly as they were written.", "Henry David Thoreau", "Walden"],
  ["It was a bright cold day in April, and the clocks were striking thirteen.", "George Orwell", "Nineteen Eighty-Four"],
  ["That is part of the beauty of all literature — you discover your longings are universal longings.", "F. Scott Fitzgerald", null],
  ["It was the best of times, it was the worst of times.", "Charles Dickens", "A Tale of Two Cities"],
  ["Write what should not be forgotten.", "Isabel Allende", null],
  ["Either write something worth reading or do something worth writing.", "Benjamin Franklin", null],
  ["The true sign of intelligence is not knowledge but imagination.", "Albert Einstein", null],
  ["The library is an arena of possibility, opening both a window into the soul and a door onto the world.", "Rita Dove", null],
  ["A library is not a luxury but one of the necessities of life.", "Henry Ward Beecher", null],
  ["We are made of star-stuff.", "Carl Sagan", "Cosmos"],
  ["Learning to read is probably the most difficult and revolutionary thing that happens to the human brain.", "Malcolm Gladwell", null],
  ["I try to leave out the parts that people skip.", "Elmore Leonard", null],
  ["Books are the mirrors of the soul.", "Virginia Woolf", null],
  ["Rule number one is to write every day, because writing is like everything else — the more you do it, the better you get.", "Christopher Paul Curtis", null],
  ["Next to trying and winning, the best thing is trying and failing.", "L.M. Montgomery", "Anne of Green Gables"],
  ["Once you choose hope, anything's possible.", "Christopher Reeve", null],
  ["The best of book-lovers, however, are those who make the wisest use of the books they read.", "Sarah Josepha Hale", null],
  ["The wound is the place where the light enters you.", "Rumi", null],
  ["Not everything that is faced can be changed, but nothing can be changed until it is faced.", "James Baldwin", null],
  ["Books are the plane, and the train, and the road. They are the destination, and the journey. They are home.", "Anna Quindlen", null],
  ["There is more to life than being a caterpillar.", "Lewis Carroll", "Alice's Adventures in Wonderland"],
  ["Reading is a discount ticket to everywhere.", "Mary Schmich", null],
  ["Turn your wounds into wisdom.", "Oprah Winfrey", null],
  ["Children know perfectly well that unicorns aren't real, but they also know that books about unicorns, if they are good, are true books.", "Ursula K. Le Guin", null],
  ["It is a mistake to think you can solve any major problems just with potatoes.", "Douglas Adams", "Life, the Universe and Everything"],
  ["Start writing, no matter what. The water does not flow until the faucet is turned on.", "Louis L'Amour", null],
  ["A ship in harbor is safe, but that is not what ships are built for.", "John A. Shedd", null],
  ["It's no use going back to yesterday, because I was a different person then.", "Lewis Carroll", "Alice's Adventures in Wonderland"],
  ["Curiouser and curiouser!", "Lewis Carroll", "Alice's Adventures in Wonderland"],
  ["Until I feared I would lose it, I never loved to read. One does not love breathing.", "Harper Lee", "To Kill a Mockingbird"],
  ["Beauty is truth, truth beauty — that is all ye know on earth, and all ye need to know.", "John Keats", "Ode on a Grecian Urn"],
  ["Art is never finished, only abandoned.", "Leonardo da Vinci", null],
  ["The most important stories are the ones we tell ourselves.", "V.E. Schwab", null],
  ["Knowing yourself is the beginning of all wisdom.", "Aristotle", null],
  ["You know you've read a good book when you turn the last page and feel a little as if you have lost a friend.", "Paul Sweeney", null],
  ["There are far, far better things ahead than any we leave behind.", "C.S. Lewis", null],
  ["Time is an illusion. Lunchtime doubly so.", "Douglas Adams", "The Hitchhiker's Guide to the Galaxy"],
  ["The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt", null],
  ["All this happened, more or less.", "Kurt Vonnegut", "Slaughterhouse-Five"],
  ["A good library will never be too neat, because somebody will always be taking books off the shelves.", "Lemony Snicket", null],
  ["If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", "Haruki Murakami", "Norwegian Wood"],
  ["You yourself, as much as anybody in the entire universe, deserve your love and affection.", "Buddha", null],
  ["There is a good deal of poetry in an unopened book.", "Charles Lamb", null],
  ["My alma mater was books, a good library. I could spend the rest of my life reading, just satisfying my curiosity.", "Malcolm X", null],
  ["Literature is the most agreeable way of ignoring life.", "Fernando Pessoa", null],
  ["Perhaps no place in any community is so totally democratic as the town library.", "Lady Bird Johnson", null],
  ["We are of the opinion that it is better to let books wear out by being read than let them grow moldy behind a grating.", "Jules Verne", null],
  ["Sleep is good, he said, and books are better.", "George R.R. Martin", "A Clash of Kings"],
  ["You cannot swim for new horizons until you have courage to lose sight of the shore.", "William Faulkner", null],
  ["Books, like friends, should be few and well chosen.", "Samuel Paterson", null],
  ["New beginnings are often disguised as painful endings.", "Lao Tzu", null],
  ["I have found the most valuable thing in my wallet is my library card.", "Laura Bush", null],
  ["No two persons ever read the same book.", "Edmund Wilson", null],
  ["Whatever our souls are made of, his and mine are the same.", "Emily Brontë", "Wuthering Heights"],
  ["You fail only if you stop writing.", "Ray Bradbury", null],
  ["Literature is my Utopia. Here I am not disenfranchised.", "Helen Keller", "The Story of My Life"],
  ["The past is never dead. It's not even past.", "William Faulkner", "Requiem for a Nun"],
  ["I love deadlines. I love the whooshing noise they make as they go by.", "Douglas Adams", null],
  ["Not all those who wander are lost.", "J.R.R. Tolkien", "The Fellowship of the Ring"],
  ["If you wish to make an apple pie from scratch, you must first invent the universe.", "Carl Sagan", "Cosmos"],
  ["Maybe this is why we read, and why in moments of darkness we return to books: to find words for what we already know.", "Alberto Manguel", "A Reading Diary"],
  ["Imagination is the only weapon in the war against reality.", "Lewis Carroll", "Alice in Wonderland"],
  ["She read books as one would breathe air, to fill up and live.", "Annie Dillard", null],
  ["Whatever you do, you need courage. Whatever course you decide upon, there is always someone to tell you that you are wrong.", "Ralph Waldo Emerson", null],
  ["I am not afraid of storms, for I am learning how to sail my ship.", "Louisa May Alcott", "Little Women"],
  ["Reading makes immigrants of us all. It takes us away from home, but more important, it finds home for us everywhere.", "Jean Rhys", null],
  ["There are many little ways to enlarge your world. Love of books is the best of all.", "Jacqueline Kennedy Onassis", null],
  ["I have not the talent of conversing easily with people I have never seen before.", "Jane Austen", "Pride and Prejudice"],
  ["Imagination will often carry us to worlds that never were. But without it, we go nowhere.", "Carl Sagan", null],
  ["Fiction reveals truths that reality obscures.", "Jessamyn West", null],
  ["Insanity is doing the same thing over and over again and expecting different results.", "attributed, origin disputed", null],
  ["The greatest wealth is to live content with little.", "Plato", null],
  ["The world was hers for the reading.", "Betty Smith", "A Tree Grows in Brooklyn"],
  ["What is written without effort is in general read without pleasure.", "Samuel Johnson", null],
  ["A trained librarian is a powerful search engine with a heart.", "Sarah McIntyre", null],
  ["There is no surprise more magical than the surprise of being loved. It is the finger of God on a man's shoulder.", "Charles Morgan", null],
  ["It is what you read when you don't have to that determines what you will be when you can't help it.", "Oscar Wilde", null],
  ["She was unstoppable, not because she did not have failures or doubts, but because she continued on despite them.", "Beau Taplin", null],
  ["Think before you speak. Read before you think.", "Fran Lebowitz", null],
  ["Even the smallest person can change the course of the future.", "J.R.R. Tolkien", "The Fellowship of the Ring"],
  ["I think books are like people — they'll turn up in your life when you most need them.", "Emma Thompson", null],
  ["I have always imagined that Paradise will be a kind of library.", "Jorge Luis Borges", null],
  ["Yet each man kills the thing he loves.", "Oscar Wilde", "The Ballad of Reading Gaol"],
  ["People can lose their lives in libraries. They ought to be warned.", "Saul Bellow", null],
  ["You must write, and read, as if your life depended on it.", "Adrienne Rich", null],
  ["Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "Rumi", null],
  ["A friend to all is a friend to none.", "Aristotle", null],
  ["We read to know we are not alone.", "William Nicholson", "Shadowlands"],
  ["So we beat on, boats against the current, borne back ceaselessly into the past.", "F. Scott Fitzgerald", "The Great Gatsby"],
  ["In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost", null],
  ["Between the world and me.", "James Baldwin", null],
  ["Don't panic.", "Douglas Adams", "The Hitchhiker's Guide to the Galaxy"],
  ["Give me a man or woman who has read a thousand books and you give me an interesting companion.", "Anne Rice", "The Witching Hour"],
  ["The past is a foreign country; they do things differently there.", "L.P. Hartley", "The Go-Between"],
  ["Every great story seems to begin with a snake.", "Nicolas Cage", null],
  ["I am not the same, having seen the moon shine on the other side of the world.", "Mary Anne Radmacher", null],
  ["There is creative reading as well as creative writing.", "Ralph Waldo Emerson", null],
  ["There is beauty in simplicity that will always surpass any attempt to improve it with complexity.", "Bryant McGill", null],
  ["Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", "Lao Tzu", "Tao Te Ching"],
  ["It has become almost a cliché to remark that nobody nowadays believes in progress.", "Ursula K. Le Guin", null],
  ["Faithless is he that says farewell when the road darkens.", "J.R.R. Tolkien", "The Fellowship of the Ring"],
  ["Fantasy is hardly an escape from reality. It's a way of understanding it.", "Lloyd Alexander", null],
  ["What a blessing it is to love books as I love them — to converse with the dead, and to live amidst the unreal.", "Thomas Babington Macaulay", null],
  ["To live is the rarest thing in the world. Most people exist, that is all.", "Oscar Wilde", null],
  ["Wear your bookish heart on your sleeve. It's the best kind to wear.", "Rainbow Rowell", null],
  ["The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", "Henry Ford", null],
  ["Simplicity is the ultimate sophistication.", "Leonardo da Vinci", null],
  ["Reading is an active, imaginative act; it takes work.", "Khaled Hosseini", null],
  ["The gods are dysfunctional and so is the whole freaking world.", "Rick Riordan", "Percy Jackson & the Olympians"],
  ["I write to find out what I think.", "Joan Didion", null],
  ["Books serve to show a man that those original thoughts of his aren't very new after all.", "Abraham Lincoln", null],
  ["The universe is not only stranger than we imagine, it is stranger than we can imagine.", "J.B.S. Haldane", null],
  ["Reading lets us live in someone else's shoes. Literature builds bridges; it makes our world larger.", "R.F. Kuang", "Yellowface"],
  ["Life is like riding a bicycle. To keep your balance you must keep moving.", "Albert Einstein", null],
  ["Reading should not be presented to children as a chore. It should be offered as a gift.", "Kate DiCamillo", null],
  ["You can't wait for inspiration. You have to go after it with a club.", "Jack London", null],
  ["Books may well be the only true magic.", "Alice Hoffman", "Magic Lessons"],
  ["We don't need a list of dos and don'ts. We need books, time, and silence.", "Philip Pullman", null],
  ["They say in every library there is a single book that can answer the question that burns like a fire in the mind.", "Lemony Snicket", null],
  ["The magic thread of literature runs through every human being; you just need to catch it and follow it.", "Isabel Allende", null],
  ["Literature is the safe and traditional vehicle through which we learn about the world.", "Laurie Anderson", null],
  ["Reading is to the mind what exercise is to the body.", "Joseph Addison", null],
  ["I declare after all there is no enjoyment like reading!", "Jane Austen", "Pride and Prejudice"],
  ["The world breaks everyone, and afterward, some are strong at the broken places.", "Ernest Hemingway", "A Farewell to Arms"],
  ["Water, water, everywhere, nor any drop to drink.", "Samuel Taylor Coleridge", "The Rime of the Ancient Mariner"],
  ["Once you learn to read, you will be forever free.", "Frederick Douglass", null],
  ["Silence is a source of great strength.", "Lao Tzu", "Tao Te Ching"],
  ["Your face is a book, where men may read strange matters.", "William Shakespeare", "Macbeth"],
  ["If you have a garden and a library, you have everything you need.", "Marcus Tullius Cicero", null],
  ["The woods are lovely, dark and deep, but I have promises to keep.", "Robert Frost", "Stopping by Woods on a Snowy Evening"],
  ["Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", "Rumi", null],
  ["A house without books is like a room without windows.", "Heinrich Mann", null],
  ["Knowing others is wisdom, knowing yourself is enlightenment.", "Lao Tzu", "Tao Te Ching"],
  ["A well-read woman is a dangerous creature.", "Lisa Kleypas", "A Wallflower Christmas"],
  ["Two roads diverged in a wood, and I— I took the one less traveled by.", "Robert Frost", "The Road Not Taken"],
  ["We are what we pretend to be, so we must be careful about what we pretend to be.", "Kurt Vonnegut", "Mother Night"],
  ["'Classic' — a book which people praise and don't read.", "Mark Twain", "Following the Equator"],
  ["It is a great thing to start life with a small number of really good books which are your very own.", "Arthur Conan Doyle", null],
  ["A great library is one nobody notices because it is always there, and always has what people need.", "Vicki Myron", null],
  ["The unexamined life is not worth living.", "Socrates", null],
  ["A book lying idle on a shelf is wasted ammunition — a book is not only a friend, it makes friends for you.", "Kathleen Norris", null],
  ["You can tell a lot about a person from the library books they borrow.", "Freya Sampson", "The Last Chance Library"],
  ["I can resist everything except temptation.", "Oscar Wilde", "Lady Windermere's Fan"],
  ["I was with book, as a woman is with child.", "C.S. Lewis", null],
  ["Half my life is an act of revision.", "John Irving", null],
  ["If you would tell me the heart of a man, tell me not what he reads, but what he rereads.", "François Mauriac", null],
  ["Book love is one of the most precious of possessions.", "Arthur Conan Doyle", null],
  ["The first draft of anything is garbage.", "Ernest Hemingway", null],
  ["The difference between the right word and the almost right word is the difference between lightning and a lightning bug.", "Mark Twain", null],
  ["Tell all the truth but tell it slant.", "Emily Dickinson", null],
  ["It is only with the heart that one can see rightly; what is essential is invisible to the eye.", "Antoine de Saint-Exupéry", "The Little Prince"],
  ["A room without books is like a body without a soul.", "Cicero", null],
  ["Courage is the first of human qualities because it is the quality which guarantees all others.", "Aristotle", null],
  ["The truth is rarely pure and never simple.", "Oscar Wilde", "The Importance of Being Earnest"],
  ["A tale never loses in the telling.", "J.R.R. Tolkien", null],
  ["One must always be careful of books, for words have the power to change us.", "Cassandra Clare", "Clockwork Angel"],
  ["Educating the mind without educating the heart is no education at all.", "Aristotle", null],
  ["It's not that I'm so smart, it's just that I stay with problems longer.", "Albert Einstein", null],
  ["Reality doesn't always give us the life that we desire, but we can always find what we desire between the pages of books.", "Adelise M. Cullens", null],
  ["Read in order to live.", "Gustave Flaubert", null],
  ["There is no such thing as a child who hates to read; there are only children who have not found the right book.", "Frank Serafini", null],
  ["Wear the old coat and buy the new book.", "Austin Phelps", null],
  ["Think of me and I'll think of you.", "L.M. Montgomery", "Anne of Green Gables"],
  ["I wandered lonely as a cloud.", "William Wordsworth", "I Wandered Lonely as a Cloud"],
  ["All grown-ups were once children, although few of them remember it.", "Antoine de Saint-Exupéry", "The Little Prince"],
  ["The whole world opened to me when I learned to read.", "Mary McLeod Bethune", null],
  ["Outside of a dog, a book is man's best friend. Inside of a dog, it's too dark to read.", "Groucho Marx", null],
  ["Be yourself; everyone else is already taken.", "Oscar Wilde", null],
  ["A reader lives a thousand lives before he dies.", "George R.R. Martin", "A Dance with Dragons"],
  ["I celebrate myself, and sing myself.", "Walt Whitman", "Song of Myself"],
  ["It was good to walk into a library again; it smelled like home.", "Elizabeth Kostova", "The Historian"],
  ["In a good book, the best is between the lines.", "Swedish proverb", null],
  ["At the touch of love everyone becomes a poet.", "Plato", null],
  ["Some day you will be old enough to start reading fairy tales again.", "C.S. Lewis", null],
  ["Do not go where the path may lead; go instead where there is no path and leave a trail.", "Ralph Waldo Emerson", null],
  ["You never really understand a person until you consider things from his point of view.", "Harper Lee", "To Kill a Mockingbird"],
  ["A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.", "Douglas Adams", "Mostly Harmless"],
  ["It's been my experience that you can nearly always enjoy things if you make up your mind firmly that you will.", "L.M. Montgomery", "Anne of Green Gables"],
  ["To build up a library is to create a life. It's never just a random collection of books.", "Carlos María Domínguez", null],
  ["When I let go of what I am, I become what I might be.", "Lao Tzu", "Tao Te Ching"],
  ["Three things cannot be long hidden: the sun, the moon, and the truth.", "Buddha", null],
  ["The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.", "Jane Austen", "Northanger Abbey"],
  ["Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", "C.S. Lewis", "The Four Loves"],
  ["Reading was my escape and my comfort, my consolation, my stimulant of choice: reading for the pure pleasure of it.", "Paul Auster", null],
  ["I devoured the books they lent me, then it was full satisfaction to discuss with them in the evening what I had perused.", "Charlotte Brontë", "Jane Eyre"],
  ["Everything in the world exists in order to end up as a book.", "Stéphane Mallarmé", null],
  ["One glance at a book and you hear the voice of another person, perhaps dead a thousand years. To read is to voyage through time.", "Carl Sagan", null],
  ["To acquire the habit of reading is to construct for yourself a refuge from almost all the miseries of life.", "W. Somerset Maugham", null],
  ["We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde", "Lady Windermere's Fan"],
  ["Books are mirrors: you only see in them what you already have inside you.", "Carlos Ruiz Zafón", "The Shadow of the Wind"],
  ["A good traveler has no fixed plans and is not intent on arriving.", "Lao Tzu", "Tao Te Ching"],
  ["Hope is a waking dream.", "Aristotle", null],
  ["Poetry is when an emotion has found its thought and the thought has found words.", "Robert Frost", null],
  ["Hope is the thing with feathers that perches in the soul.", "Emily Dickinson", null],
  ["Style means the right word. The rest matters little.", "Jules Renard", null],
  ["If there's a book that you want to read, but it hasn't been written yet, then you must write it.", "Toni Morrison", null],
  ["Words are pale shadows of forgotten names. As names have power, words have power.", "Patrick Rothfuss", "The Name of the Wind"],
  ["The ships hung in the sky in much the same way that bricks don't.", "Douglas Adams", "The Hitchhiker's Guide to the Galaxy"],
  ["Books were safer than other people anyway.", "Neil Gaiman", "The Ocean at the End of the Lane"],
  ["Some people without a college degree are smarter than college professors.", "Louisa May Alcott", "Little Women"],
  ["A book is a dream that you hold in your hand.", "Neil Gaiman", null],
  ["To define is to limit.", "Oscar Wilde", "The Picture of Dorian Gray"],
  ["Seldom, very seldom, does complete truth belong to any human disclosure.", "Jane Austen", "Emma"],
  ["What we think, we become.", "Buddha", null],
  ["Call me Ishmael.", "Herman Melville", "Moby-Dick"],
  ["The more that you read, the more things you will know.", "Dr. Seuss", "I Can Read with My Eyes Shut!"],
  ["The very existence of libraries affords the best evidence that we may yet have hope for the future of man.", "T.S. Eliot", null],
  ["A poem begins as a lump in the throat.", "Robert Frost", null],
  ["So he said, 'That's a turn-up for the books.'", "Tommy Cooper", null],
  ["I wish it need not have happened in my time, said Frodo. So do I, said Gandalf, and so do all who live to see such times.", "J.R.R. Tolkien", "The Fellowship of the Ring"],
  ["Writing is thinking on paper.", "William Zinsser", null],
  ["Literature and butterflies are the two sweetest passions known to man.", "Vladimir Nabokov", null],
  ["I love the sound of pages turning — it's the sound of a mind opening.", "Rebecca Solnit", null],
  ["Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson", null],
  ["I ransack public libraries, and find them full of sunk treasure.", "Virginia Woolf", null],
  ["It is not length of life, but depth of life.", "Ralph Waldo Emerson", null],
  ["Ring the bells that still can ring. Forget your perfect offering. There is a crack in everything — that's how the light gets in.", "Leonard Cohen", null],
  ["Great spirits have always encountered violent opposition from mediocre minds.", "Albert Einstein", null],
  ["Sometimes, the only way to carry on is to find the extraordinary in the ordinary.", "Rick Riordan", "The Lightning Thief"],
  ["There is nothing I would not do for those who are really my friends.", "Jane Austen", "Pride and Prejudice"],
  ["It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.", "Jane Austen", "Pride and Prejudice"],
  ["How many a man has dated a new era in his life from the reading of a book.", "Henry David Thoreau", "Walden"],
  ["Google can bring you back 100,000 answers. A librarian can bring you back the right one.", "Neil Gaiman", null],
  ["There is nothing to writing. All you do is sit down at a typewriter and bleed.", "Ernest Hemingway", null],
  ["Books can be dangerous. The best ones should be labeled 'This could change your life.'", "Helen Exley", null],
  ["Some books leave us free and some books make us free.", "Ralph Waldo Emerson", null],
  ["If a book is well written, I always find it too short.", "Jane Austen", "Northanger Abbey"],
  ["A good book has no ending.", "R.D. Cumming", null],
  ["In the middle of difficulty lies opportunity.", "Albert Einstein", null],
  ["The only thing that makes life possible is permanent, intolerable uncertainty.", "Ursula K. Le Guin", "The Left Hand of Darkness"],
  ["Extraordinary claims require extraordinary evidence.", "Carl Sagan", null],
  ["Books are a form of political action. Books are knowledge. Books are reflection.", "Toni Morrison", null],
  ["A jug fills drop by drop.", "Buddha", null],
  ["It is the mark of an educated mind to be able to entertain a thought without accepting it.", "Aristotle", null],
  ["Public libraries are the sole community centers left in America.", "Russell Banks", null],
  ["There is no greater agony than bearing an untold story inside you.", "Maya Angelou", "I Know Why the Caged Bird Sings"],
  ["If you don't like to read, you haven't found the right book.", "J.K. Rowling", null],
  ["To a bibliophile, there is but one thing better than a box of new books, and that is a box of old ones.", "Will Thomas", "Some Danger Involved"],
  ["It is our choices that show what we truly are, far more than our abilities.", "J.K. Rowling", "Harry Potter and the Chamber of Secrets"],
  ["Once we accept our limits, we go beyond them.", "Albert Einstein", null],
  ["The world of books is the most remarkable creation of man.", "Daniel J. Boorstin", null],
  ["A library is infinity under a roof.", "Gail Carson Levine", null],
  ["Kindred spirits are not so scarce as I used to think.", "L.M. Montgomery", "Anne of Green Gables"],
  ["The man who does not read good books is no better than the man who can't.", "Mark Twain", null],
  ["A blessed companion is a book — a book that fitly chosen is a lifelong friend.", "Douglas Jerrold", null],
  ["A word is a small magic, a spell that can unlock the world.", "Jane Yolen", null],
  ["Vanity and pride are different things, though the words are often used synonymously.", "Jane Austen", "Pride and Prejudice"],
  ["I'd rather be able to appreciate things I can't have than to have things I'm not able to appreciate.", "Elizabeth Gilbert", "Eat, Pray, Love"],
  ["A book is not only a friend, it makes friends for you.", "Elizabeth Hardwick", null],
  ["Words are, of course, the most powerful drug used by mankind.", "Rudyard Kipling", null],
  ["Patience is bitter, but its fruit is sweet.", "Aristotle", null],
  ["The reading of good books is like a conversation with the best men of past centuries.", "René Descartes", null],
  ["I do believe something very magical can happen when you read a good book.", "J.K. Rowling", null],
  ["To learn to read is to light a fire; every syllable that is spelled out is a spark.", "Victor Hugo", null],
  ["Books let us into their souls and lay open to us the secrets of our own.", "William Hazlitt", null],
  ["All that is gold does not glitter, not all those who wander are lost.", "J.R.R. Tolkien", "The Fellowship of the Ring"],
  ["Stories are wild creatures. When you let them loose, who knows what havoc they might wreak.", "Patrick Rothfuss", "The Name of the Wind"],
  ["A book is a version of the world. If you do not like it, ignore it, or offer your own version in return.", "Salman Rushdie", null],
  ["Happy families are all alike; every unhappy family is unhappy in its own way.", "Leo Tolstoy", "Anna Karenina"],
  ["Do you know the feeling when you start reading a new book before the membrane of the last one has had time to close?", "Diane Setterfield", "The Thirteenth Tale"],
  ["There is nothing better than a friend, unless it is a friend with chocolate.", "Linda Grayson", null],
  ["There are worse crimes than burning books. One of them is not reading them.", "Joseph Brodsky", null],
  ["Home is behind, the world ahead, and there are many paths to tread.", "J.R.R. Tolkien", "The Fellowship of the Ring"],
  ["All good books are alike in that they are truer than if they had really happened.", "Ernest Hemingway", null],
  ["Books are a uniquely portable magic.", "Stephen King", "On Writing"],
  ["When I got my library card, that was when my life began.", "Rita Mae Brown", null],
  ["Fear is that little darkroom where negatives are developed.", "Michael Pritchard", null],
  ["Nothing in life is to be feared, it is only to be understood.", "Marie Curie", null],
  ["Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon.", "Gabriel García Márquez", "One Hundred Years of Solitude"],
  ["Whatever you are, be a good one.", "Abraham Lincoln", null],
  ["The purpose of a storyteller is not to tell you how to think, but to give you questions to think upon.", "Brandon Sanderson", "The Way of Kings"],
  ["Love doesn't just sit there like a stone; it has to be made, like bread, remade all the time, made new.", "Ursula K. Le Guin", "The Lathe of Heaven"],
  ["She was never really wanted, not from any point of view.", "L.M. Montgomery", "Anne of Green Gables"],
  ["Nature does not hurry, yet everything is accomplished.", "Lao Tzu", "Tao Te Ching"],
  ["The reading of all good books is like a conversation with the finest minds of past centuries.", "René Descartes", null],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant", "The Story of Philosophy"],
  ["Why, sometimes I've believed as many as six impossible things before breakfast.", "Lewis Carroll", "Through the Looking-Glass"],
  ["The scariest moment is always just before you start.", "Stephen King", "On Writing"],
  ["In my younger and more vulnerable years my father gave me some advice I've been turning over in my mind ever since.", "F. Scott Fitzgerald", "The Great Gatsby"],
  ["I love the solitude of reading — the deep dive into someone else's story, the delicious ache of a last page.", "Naomi Shihab Nye", null],
  ["Reading fiction is important — it is a vital means of imagining a life other than our own.", "Ann Patchett", null],
  ["When I look back, I am so impressed again with the life-giving power of literature.", "Maya Angelou", null],
  ["I think, therefore I am.", "René Descartes", null],
  ["You are never too old to set another goal or to dream a new dream.", "C.S. Lewis", null],
  ["Reading furnishes the mind only with materials of knowledge; it is thinking that makes what we read ours.", "John Locke", null],
  ["I'm so glad I live in a world where there are Octobers.", "L.M. Montgomery", "Anne of Green Gables"],
  ["The trouble is, you think you have time.", "Buddha", null],
  ["Books have a unique way of stopping time and saying: let's not forget this.", "Dave Eggers", null],
  ["Every book provides a chance to try another life you could have lived.", "Matt Haig", "The Midnight Library"],
  ["Somewhere, something incredible is waiting to be known.", "Carl Sagan", null],
  ["A word after a word after a word is power.", "Margaret Atwood", null],
  ["Without libraries what have we? We have no past and no future.", "Ray Bradbury", null],
  ["There is no friend as loyal as a book.", "Ernest Hemingway", null],
  ["A classic is a book that has never finished saying what it has to say.", "Italo Calvino", "The Uses of Literature"],
  ["The Earth is a very small stage in a vast cosmic arena.", "Carl Sagan", "Pale Blue Dot"],
];

/* ---------------- gamification ---------------- */
const XP_RULES = {
  perMinute: 1, perPage: 2, finishBook: 150, firstSessionOfDay: 20,
  journalEntry: 15, deepJournalEntry: 22, review: 25, newGenre: 40,
};
const levelForXP = (xp) => Math.floor(Math.sqrt(xp / 60)) + 1;
const xpForLevel = (lv) => Math.pow(lv - 1, 2) * 60;

const ACHIEVEMENTS = [
  { id:"first_session", ic:"bookmark",   t:"First Page",        d:"Log your first reading session", test:(s)=>s.sessions.length>=1 },
  { id:"page_turner",   ic:"book",       t:"Page Turner",       d:"Read 100 pages",                 test:(s,d)=>d.totalPages>=100 },
  { id:"thousand",      ic:"layers",     t:"1,000 Pages",       d:"Read 1,000 pages",               test:(s,d)=>d.totalPages>=1000 },
  { id:"night_owl",     ic:"moon",       t:"Night Owl",         d:"Finish a session after 11pm",    test:(s)=>s.sessions.some(x=>new Date(x.createdAt).getHours()>=23||new Date(x.createdAt).getHours()<4) },
  { id:"early_bird",    ic:"sunrise",    t:"Dawn Reader",       d:"Read before 7am",                test:(s)=>s.sessions.some(x=>{const h=new Date(x.createdAt).getHours();return h>=4&&h<7}) },
  { id:"weekend",       ic:"calendar",   t:"Weekend Warrior",   d:"Read on a Saturday and Sunday",  test:(s)=>{const ds=new Set(s.sessions.map(x=>new Date(x.date+"T12:00").getDay()));return ds.has(0)&&ds.has(6)} },
  { id:"streak7",       ic:"flame",      t:"One Week Ritual",   d:"7-day reading streak",           test:(s,d)=>d.bestStreak>=7 },
  { id:"streak30",      ic:"award",      t:"30-Day Streak",     d:"30-day reading streak",          test:(s,d)=>d.bestStreak>=30 },
  { id:"finisher",      ic:"flag",       t:"The Finisher",      d:"Finish your first book",         test:(s,d)=>d.finished>=1 },
  { id:"five_books",    ic:"archive",    t:"Handful of Worlds", d:"Finish 5 books",                 test:(s,d)=>d.finished>=5 },
  { id:"marathon",      ic:"zap",        t:"Book Marathon",     d:"A single session over 90 min",   test:(s)=>s.sessions.some(x=>x.minutes>=90) },
  { id:"explorer",      ic:"compass",    t:"Genre Explorer",    d:"Finish books in 3 genres",       test:(s,d)=>d.genresFinished>=3 },
  { id:"annotator",     ic:"pen",        t:"Annotation Master", d:"Save 10 notes or quotes",        test:(s)=>s.journal.length>=10 },
  { id:"critic",        ic:"star",       t:"The Critic",        d:"Rate and review 3 books",        test:(s)=>s.books.filter(b=>b.rating&&b.review).length>=3 },
  { id:"collector",     ic:"book_open",  t:"The Collector",     d:"20 books in your library",       test:(s)=>s.books.length>=20 },
  { id:"well_rounded",  ic:"compass",    t:"Well-Rounded",      d:"Finish books in 8 different genres", test:(s,d)=>d.genresFinished>=8 },
  { id:"comeback",      ic:"sunrise",    t:"The Comeback",      d:"Finish a book after a month-long pause", test:(s)=>s.books.some(b=>{
    if (b.shelf!=="finished") return false;
    const ss=s.sessions.filter(x=>x.bookId===b.id).map(x=>x.date).sort();
    for (let i=1;i<ss.length;i++) { if ((new Date(ss[i])-new Date(ss[i-1]))/86400000>=30) return true; }
    return false;
  }) },
];

/* ---------------- profile avatars — minimal line-art reading archetypes ---------------- */
const AVATAR_PRESETS = [
  { id: "night-owl",    label: "Night Owl",     file: "icons/avatar-night-owl.png" },
  { id: "bookworm",     label: "The Bookworm",  file: "icons/avatar-bookworm.png" },
  { id: "speed-reader", label: "Speed Reader",  file: "icons/avatar-speed-reader.png" },
  { id: "romantic",     label: "The Romantic",  file: "icons/avatar-romantic.png" },
  { id: "detective",    label: "The Detective", file: "icons/avatar-detective.png" },
  { id: "dreamer",      label: "The Dreamer",   file: "icons/avatar-dreamer.png" },
];
const SESSION_MOODS = [
  ["😌","calm"],["🤯","mind-blown"],["🥹","moved"],["😱","gripped"],["😴","sleepy"],["🤔","thoughtful"]
];
const SESSION_LOCATIONS = [
  ["🛋️","couch"],["🚌","commute"],["🛏️","bed"],["☕","café"],["🌳","outside"]
];

/* ================================================================
   JOURNAL — prompt sets per reflection kind
================================================================ */
const JOURNAL_KINDS = [
  { id: "reflection", label: "Reflection", ic: "feather",   hint: "How did this book make you feel — honestly?" },
  { id: "character",  label: "Character",  ic: "eye",       hint: "Someone in these pages who stayed with you." },
  { id: "analysis",   label: "Analysis",   ic: "compass",   hint: "Engage with the craft, the argument, the structure." },
  { id: "quote",      label: "Quote",      ic: "bookmark",  hint: "The line you'd copy into a notebook." },
  { id: "letter",     label: "Letter",     ic: "sunrise",   hint: "A note to your future self — sealed until you pick." },
];

const EMOTIONAL_PROMPTS = [
  "How did this book make you feel — honestly?",
  "What was happening in your life while you read this?",
  "Where did you have to put the book down and just sit with it?",
  "What feeling did the ending leave you with?",
  "If this book were a season, which one — and why?",
];

const CHARACTER_PROMPTS = [
  "Which character felt like someone you know?",
  "Whose choices would you have made differently?",
  "Who did you find yourself rooting for, and why?",
  "Which character's flaws felt a little too familiar?",
  "Who changed the most — and did you believe it?",
];

const ANALYSIS_PROMPTS = [
  "What is this book really about, beneath the plot?",
  "How does the structure or pacing serve the theme?",
  "What would you argue with a critic — or the author — about?",
  "What technique did the author use that stood out to you?",
  "What does this book borrow from, or push back against?",
];
